
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
      - echo job1 done
  - job: Job2
    steps:
      - echo job2 done

- stage: Dev
  jobs:
  - job: Job1
    steps:
      - echo job1 done
  - job: Job2
    steps:
      - echo job2 done

- stage: Uat
  dependsOn:
  - Build
  - Dev
  jobs:
  - job: Job1
    steps:
      - echo job1 done
  - job: Job2
    steps:
      - echo job2 done
