
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Job1
    steps: 
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version 
    - bash: mvn -version 
    - bash: ls -R $(Build.ArtifactStagingDirectory)
  
# - stage: Dev
#   jobs:
#   - job: Job1
#     steps: 
#       - script: echo job1 done
#   - job: Job2
#     steps:
#       - script: echo job2 done


# - stage: Uat
#   dependsOn:
#   - Build
#   - Dev
#   jobs:
#   - job: Job1
#     steps: 
#       - script: echo job1 done
#   - job: Job2
#     steps:
#       - script: echo job2 done

